### ISSUE TITLE
Questions steps 5 and 6 ?

### ISSUE THREAD

**Issue by Mr-Coquin** [luyadev/luya-module-userauth#10]
Can you elaborate on steps 5 and 6? Not quite sure where to put it?

I also wanted to know if there is any possibility for users to register themselves and have some kind of personal account?

**Comment by nadar** [comment]
The readme says:

> Authsystem with username and password for a given cms page area. It does not contain a registration process for new users in the frontend!.

5. use the module block or set the page as type module. its an old video, with different design, but functionality is the same: https://www.youtube.com/watch?v=nHxV-ke8CVw&list=PLt0F-ltCO67Q7jXRUA2LoSqIpe6gBkqAQ&index=3

**Comment by Mr-Coquin** [comment]
I used as module block. And the form appeared.
![image](https://github.com/luyadev/luya-module-userauth/assets/123034940/dbfdbc29-fb27-4387-bd5c-24a27ba7c266)
![image](https://github.com/luyadev/luya-module-userauth/assets/123034940/0365ef9c-b36d-4c28-8fb1-2d41518e6df7)
But based on the description in step 5. it is necessary to add something and here it is not entirely clear to me what and where.
![image](https://github.com/luyadev/luya-module-userauth/assets/123034940/0e215d58-f6f6-4a4f-bced-93dfa1b3fc7e)
And is there any ready-made example of registration for users on the frontend ???

**Comment by nadar** [comment]
1. The login looks correct, thats it what it is.
2. as already mentioned, there is no registration process. You have to do everything by yourself.
