### ISSUE TITLE
Help with luya-module-userauth

### ISSUE THREAD

**Issue by kvonosan** [luyadev/luya-module-userauth#5]
### What steps will reproduce the problem?
I am installed luya-module-userauth last version on luya version:
luyadev/luya-bootstrap3            1.0.7   LUYA Bootstrap 3 content
luyadev/luya-composer              1.0.6   LUYA composer core
luyadev/luya-core                  1.0.25  LUYA is a scalable web framework and content management system with the goal to please developers, clie...
luyadev/luya-generic               1.0.4   LUYA Generic content
luyadev/luya-module-admin          2.4.1   Administration core module for all LUYA admin modules
luyadev/luya-module-cms            2.2.1   The LUYA CMS module provides a full functional Content Management System for adding contents based on b...
luyadev/luya-testsuite             1.0.26  TestCases and Data for LUYA Modules and Components. Makes testing less pain.

after install i am started luya migrate and luya import. i am load homepage luya and get result 
Invalid Configuration – yii\base\InvalidConfigException
Unable to find the requested cms layout '1' for nav item page id '2'. Make sure your page does not have an old inactive/deleted cms layout selected.

### What is the expected result?
loaded homepage

### What do you get instead? (A Screenshot can help us a lot!)
![image](https://user-images.githubusercontent.com/13044556/83945542-8ec17e80-a835-11ea-8e91-aa0aab42c668.png)

Probably it is a not bug, but me need help for understand what's happened, please help me.

**Comment by nadar** [comment]
Hey @kvonosan 

Take a closer look at the error message which is displayed:

> Unable to find the requested cms layout '1' for nav item page id '2'. Make sure your page does not have an old inactive/deleted cms layout selected.

So, maybe this is because the page your visiting has a cmslayout assigned which does not exists anymore. Maybe because you have renamed the cmslayout file and run import for example. So just edit the page and set a valid cmslayout file.

**Comment by kvonosan** [comment]
Yes i it understand, but where my Page is state does not have an old inactive, but it is active and not old. Sorry but stupid question.

**Comment by kvonosan** [comment]
I am not edit layout.

**Comment by kvonosan** [comment]
And a i am not renamed cms layout. It is only when i am installed auth module. Sorry for my english.

**Comment by nadar** [comment]
As you can see from the stack trace, its unable to find the layout (which is a cmslayout in this case https://luya.io/guide/app-cmslayouts) 

Check the cms layout for the given page you are trying to access:

<img width="1593" alt="Bildschirmfoto 2020-06-06 um 21 48 50" src="https://user-images.githubusercontent.com/3417221/83953284-8bcb8b80-a83f-11ea-90ac-cb7624edb4a7.png">

**Comment by kvonosan** [comment]
Problem is a when i get pages in admin module - it is write login Page.

**Comment by nadar** [comment]
What version of luya admin, cms and core? Composer.json?

kvonosan <notifications@github.com> schrieb am Sa., 6. Juni 2020, 21:48:

**Comment by kvonosan** [comment]
And server error 50*. I don't remember which one exactly

**Comment by kvonosan** [comment]
Cms and core Version in first post. Composer I can't watch it now. If it require i am watch it tommorow.

**Comment by nadar** [comment]
use admin ^3.0 and cms ^3.0 and run composer update, also the latest core release ist 1.4.1.

If you remove the userauth module from the bootstrap section, it works you say? I need more infos, more details to debug and try to reproduce your problem.

**Comment by kvonosan** [comment]
i am use composer version 1.9.0.
sorry but I remembered that I was editing layout main.php in @app/views/layouts. I didn't execute the luya import command, I just didn't know it needed to be executed, but the file itself main.php I didn't rename it, but when I installed the userauth module, I executed the luya import command. How do you think this could have affected this error? Maybe after each source editing main.php need to do luya import? by the way, I installed the latest versions of luya and luya-cms from scratch and tried to install the userauth module and got an error. I took a screenshot. in the settings I did not change the language and left English
![image](https://user-images.githubusercontent.com/13044556/83969072-ecb69a80-a8f7-11ea-91ce-950e3c9897c1.png)
 there is still a chance that this is due to an incorrectly configured language in my config on old site

'admin' => [
            'class' => 'luya\admin\Module',
            'secureLogin' => false, // when enabling secure login, the mail component must be proper configured otherwise the auth token mail will not send.
            'strongPasswordPolicy' => false, // If enabled, the admin user passwords require strength input with special chars, lower, upper, digits and numbers
            'interfaceLanguage' => 'en', // Admin interface default language. Currently supported: en, de, ru, es, fr, ua, it, el, vi, pt, fa
        ],

'composition' => [
            'hidden' => true, // no languages in your url (most case for pages which are not multi lingual)
            'default' => ['langShortCode' => 'ru'], // the default language for the composition should match your default language shortCode in the language table.
        ],


where is the bootstrap located?

**Comment by kvonosan** [comment]
I seem to understand what the error is, but I do not know how to fix it, the fact is that in the database in the table cms_nav_item in a row with page id = 2 lang_id = 2,
![image](https://user-images.githubusercontent.com/13044556/83969247-1f14c780-a8f9-11ea-8547-86ffa3d97bc8.png)
when I put 1, I got an error in the screenshot below, so just not generated a page for lang id = 1 for record with id =1
![image](https://user-images.githubusercontent.com/13044556/83969289-6307cc80-a8f9-11ea-9828-46db0b26266a.png)
I will try to update the luya version to the version admin ^3.0 and cms ^3.0

**Comment by nadar** [comment]
Just install: https://github.com/luyadev/luya-kickstarter (https://luya.io/guide/install) and never change somethings in vendor. Then everything should work out of the box.

If everything works install the user auth module: https://github.com/luyadev/luya-module-userauth and follow the instructions, this will require you to do certain steps: https://github.com/luyadev/luya-module-userauth#installation

1. The first error from your screenshots seems that you missed to install the admin module... Because the requested trait exists: https://luya.io/api/luya-admin-traits-TaggableTrait
2. The second error from the screenshots explains exactly: you are missing to set a page as "HOME" (default) page, make sure the installed language and composition lang short code are the same.

**Comment by kvonosan** [comment]
i am install new luya, and upgrade it, and install luya-module-userauth, i add module in page and it work correctly.
